### ISSUE TITLE
"Run project" fails on windows if the username contains an apostrophe

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [jsoftware/qtide#1]
I recently started using the J IDE, and was really impressed with what I saw. However, upon trying to run the project I had made, I received this error:

```
   
|open quote
|   load 'c:/users/conor o'brien/j64-805-user/projects/jjelly/build.ijs'
|                                                                      ^
   load 'c:/users/conor o'brien/j64-805-user/projects/jjelly/run.ijs'
|open quote
|   load 'c:/users/conor o'brien/j64-805-user/projects/jjelly/run.ijs'
|                                                                    ^
   
```

I assume this is because my username contains an apostrophe, which would trigger the syntax error. (I believe this is also a problem with running the `plot` package.)

**Comment by cdburke** [comment]
Thanks! I will get this fixed. For now you will have to run that load command with doubled quotes, i.e. 

... o''brien ...

**Comment by cdburke** [comment]
The IDE binaries need to be rebuilt and we will get this done over the weekend.

In the meantime, you could move the installation and user directory (or reinstall) out of your home. Any other directory without a quote in the name should work.

**Comment by cdburke** [comment]
This should be fixed now. You can download new binaries using updatejqt.cmd. The IDE version will be 1.5.4.

**Comment by bilam** [comment]
close
