### ISSUE TITLE
Missing shared object

### ISSUE THREAD

**Issue by morpheusthewhite** [jsoftware/qtide#3]
After building the project (running `qmake --version` results in `QMake version 3.0
Using Qt version 5.7.1 in /usr/lib/x86_64-linux-gnu`) I try to lauch the executable from `bin/linux-x86_64/release` but it exits with 
```
Load library /home/morpheusthewhite/bin/qtide/bin/linux-x86_64/release/libj.so failed.
```

That folder contains `jqt  libjqt.so  libjqt.so.1  libjqt.so.1.7  libjqt.so.1.7.9`

**Comment by bilam** [comment]
not applicable. executable is not designed to launch inside that folder.
