### ISSUE TITLE
wcwidth should be used to measure visual width of Unicode string

### ISSUE THREAD

**Issue by zhihaoy** [jsoftware/qtide#4]
A boxed string of UTF-8 encoding is displayed as
```
┌──────────────────────────────────────────────┐
│C:\Users\zy\devel\jsource\makevs\jdll\测试.npy│
└──────────────────────────────────────────────┘
```
The last vertical bar is not aligned correctly.  Chinese characters' width should be `wcwidth`.

**Comment by bilam** [comment]
are you using a fixed pitch font?

**Comment by zhihaoy** [comment]
> are you using a fixed pitch font?

That seems to be the problem.  Thanks.
