### ISSUE TITLE
'NB.' in editor

### ISSUE THREAD

**Issue by rdm** [jsoftware/qtide#6]
The literal 'NB.' in the jqt editor currently highlights as a comment (including the rest of the line) rather than as a literal.

**Comment by cdburke** [comment]
For reference, the highlighting code is at

https://github.com/jsoftware/qtide/blob/master/lib/high/highj.cpp

**Comment by bilam** [comment]
Isn't this the correct behavior?
The same would be done for comment markers in other programming languages.
eg in C
// this is a comment

**Comment by rdm** [comment]
Does the C support highlight `"// this is a string"` in the same way that it highlights `// this is a comment`?

**Comment by bilam** [comment]
Sorry! I had misread your message.
