### ISSUE TITLE
arbitrary keyboard and mouse events for controls

### ISSUE THREAD

**Issue by rdm** [jsoftware/qtide#7]
I should be able to request keyboard and mouse event for a control, when it has focus. Edit: actually, the problem here is that I do not know how to receive those events.

(In this context, the distinction between parent control and child control is probably not relevant, except if that makes implementation significantly easier.)

Edit: this paragraph is almost certainly not relevant, but left here for historical integrity: _This would require an extension to the 'wd' language. (Or, if this mechanism has already been implemented, it should be documented at https://code.jsoftware.com/wiki/Guides/Window_Driver/Event_Handling#.)_

**Comment by cdburke** [comment]
By design the events reported depend on the control, and should be appropriate for the control. So an edit control will get keyboard events and an graphics control will get mouse events. A button would get neither, but would get a button event.

Are there specific events that you would like to add for a control?

**Comment by rdm** [comment]
My motivation, in this context, was http://www.rosettacode.org/wiki/Robots which asks us to implement https://en.wikipedia.org/wiki/Chase_(video_game)

Here, we need directional controls, and the events on arrow keys (or wasd or hjkl) would be ideal.

It's possible to implement using some other mechanism. But it occurs to me that graphics controls have also had keyboard events, so presumably they still do. I just do not know where that's documented, and I don't know how many experiments I should expect to perform to (re-)discover this kind of information.

**Comment by bilam** [comment]
For this application, I think it will be easier to use isidraw instead of isigraph. isidraw doesn't need any paint event to work.

**Comment by rdm** [comment]
I am agnostic about isidraw vs. isigraph - and, generaly speaking, I would probably prefer isidraw over isigraph.

That said, I am not getting any events from this:

```
wd {{)n
  pc game closeok;
  cc chase isidraw;
  pshow;
}}

game_chase_isidraw=: {{
  echo y
}}

game_handler=: {{
  echo y
}}

require'~addons/ide/qt/gl2.ijs'
coinsert'jgl2'
glclear''

```

And I guess that that is my real issue here. (Also, I should maybe mention jqt has a tendency to crash on me with this kind of code, though I have not yet figured out how to make that reproducible and it might be an unrelated issue.)

**Comment by bilam** [comment]
There is no such thing as a "isidraw" event. There may be resize event but I am not sure.
You can just paint to isidraw at any time you like. eg, after the 
glclear''
gllines 10 20 12 20 30 10
glpaint''    NB. update isidraw

Try drawing with gl2 commands inside keyboard events or timer event handler.

**Comment by rdm** [comment]
I am not looking for an isidraw event.

I am looking for an isidraw event handler.

According to https://code.jsoftware.com/wiki/Guides/Window_Driver/Event_Handling 

> An event handler is a verb that is invoked when a Windows event occurs, for example, when a button is pressed. The standard event handling mechanism in J supports four levels of event handler for a given form. If the form name is abc, these are:
> 
> abc_handler (the override handler)
> abc_id_class (the child handler, e.g. abc_pressme_button)
...

And, in this context I believe I should replace 'abc' with 'game', and 'id' with 'chase' and 'class' with 'isidraw'.

**Comment by tikkanz** [comment]
In case it helps the 'games/2048' addon implements directional keyboard events.

**Comment by rdm** [comment]
Hmm... games/2048 seems to have arranged so that arrow keys are menu shortcuts.

That's an interesting approach.

**Comment by rdm** [comment]
I am closing this issue.

The 'game_handler' event handler should have been emitting blank lines, and that bothers me. But other than that, I was too far off track here for this to be a meaningful issue.
